### PR TITLE
Force never using RENDER_SEPARATE_THREAD because it's broken on switch

### PR DESCRIPTION
**Pull request by EIREXE**

### CODE REVIEW

**Comment by Stary2001** [comment]
I suspect this can be fixed properly by implementing OS::{make,release}_rendering_thread(), do you have a specific test case for it being broken (ie is it just always broken or sometimes)?

**Comment by EIREXE** [comment]
> I suspect this can be fixed properly by implementing OS::{make,release}_rendering_thread(), do you have a specific test case for it being broken (ie is it just always broken or sometimes)?

It appears to always be broken in my case, my game defaults to using multi threaded rendering, so I thought it would be a good idea to prevent it from being used at all since the engine appears to crash on startup if it's used.

**Comment by Stary2001** [comment]
OK - I just quickly tested and it still crashes with those implemented, although getting slightly further into the engine (godot logo gets shown).
The default rendering mode is RENDER_THREAD_SAFE - do you see a performance difference between _SAFE and _UNSAFE? I'd rather map multi threaded to _SAFE, as we have other non-graphics threads.

**Comment by EIREXE** [comment]
> OK - I just quickly tested and it still crashes with those implemented, although getting slightly further into the engine (godot logo gets shown).
> The default rendering mode is RENDER_THREAD_SAFE - do you see a performance difference between _SAFE and _UNSAFE? I'd rather map multi threaded to _SAFE, as we have other non-graphics threads.

You are right, we should be using _SAFE

**Pull request merged**
