### PR TITLE
Fix user directory access

### PR DESCRIPTION
**Pull request by EIREXE**

### CODE REVIEW

**Comment by Stary2001** [comment]
This seems fine, though I'd prefer a better fallback in the app_name=="" case (get_resource_dir() is empty except on Android).

**Comment by EIREXE** [comment]
> This seems fine, though I'd prefer a better fallback in the app_name=="" case (get_resource_dir() is empty except on Android).

I copied this fallback from the OSWindows implementation, what do you suggest we do instead? fallback to sdmc:/switch/godot/__unknown or something like that?

**Comment by Stary2001** [comment]
Yeah, that sounds reasonable.

**Comment by EIREXE** [comment]
> Yeah, that sounds reasonable.

I think this should be it

**Pull request merged**
